### ISSUE TITLE
sass leading partial underscore not recogized in file name.

### ISSUE THREAD

**Issue by dkebler** [mrjoelkemp/sublime-dependents#101]
Looking at the console dependents doesn't know about the _ underscore convention in sass/scss.

For example  @import 'color'   
sass compilers will attempt to  import  color.scss, or _color.scss.    but dependents just looks for file without the _.

Sass guideline/best practices suggest using the _ partial and that is the way my entire sass architecture is set up.   

Any setting fix this? or needs to be in the python code?

**Comment by mrjoelkemp** [comment]
Thanks for reporting the issue @dkebler. This is a tricky one.

For the "jump to dependency" feature, I could just add this logic into the python code. However, the "find dependents" feature is definitely trickier. I'll have to think about a fix that could apply all around. Will report back soon.

**Comment by mrjoelkemp** [comment]
Hey @dkebler. I fixed the issue in the newly released version 2.4.5. Thanks again for contributing!

**Comment by dkebler** [comment]
Report: works great both ways now!  thanks so much!  A small but very nice
package for navigating around my code especially since I follow sass
guidelines and break my code into many organized partials.

On Sun, Feb 8, 2015 at 8:09 PM, Joel Kemp <notifications@github.com> wrote:

> Hey @dkebler <https://github.com/dkebler>. I fixed the issue in the newly
> released version 2.4.5. Thanks again for contributing!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/sublime-dependents/issues/101#issuecomment-73455141>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Thanks for the kind words @dkebler. 

> A small but very nice package for navigating around 

Before I forget, how did you find out about the plugin? Just curious.

Indeed, the feature set for Sass is pretty small. JS has a few more features, but Sass could use more love. I'm totally open to any feature requests that would make it easier to understand and traverse your code. 

Thanks again.

**Comment by dkebler** [comment]
Can't remember how I found out.   Searching package control for @import or
sass or scss does not bring it up so I would include those in the page tags
(and/or documentation/readme).

If you can address the file path subdirectories issue I posted last night
this would be a complete tool for navigating sass code.  Too because the
super key is problematic I wrote up a both a windows and linux key and
mouse binding that works better.  Let me get you a pull request for those
and a little improvement to your documentation.

Given the above I would then contact this fellow http://hugogiraudel.com/.
He is a sass "god" imho and he has many followers so a tweet mentioning him
will get exposure.   Here is his file/path sass guideline I am more or less
following. http://sass-guidelin.es/#the-7-1-pattern

Like I said this package is a real workflow speed improvement.  Hold down a
couple of keys and click and I can navigate a complex file architecture.
It really compliments Hugo's guidelines.  Covering all bases have you
thought of a textmate and atom version too?

On Mon, Feb 9, 2015 at 5:20 AM, Joel Kemp <notifications@github.com> wrote:

> Thanks for the kind words @dkebler <https://github.com/dkebler>.
>
> A small but very nice package for navigating around
>
> Before I forget, how did you find out about the plugin? Just curious.
>
> Indeed, the feature set for Sass is pretty small. JS has a few more
> features, but Sass could use more love. I'm totally open to any feature
> requests that would make it easier to understand and traverse your code.
>
> Thanks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/sublime-dependents/issues/101#issuecomment-73506975>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
> Given the above I would then contact this fellow http://hugogiraudel.com/.

Great tip. Will definitely do that when the sass bugs are ironed out.

> Covering all bases have you thought of a textmate and atom version too?

Definitely, but I don't have the availability to handle anything but the sublime plugin. I'd love some help.

The bulk of the logic is in nodejs npm modules, so the features can be reused across different editors.

**Comment by dkebler** [comment]
Another idea on getting the word out I'd tweet and email sublimetexttips
https://twitter.com/sublimetxttips
also sass has a twitter account.
https://twitter.com/SassCSS

On Mon, Feb 9, 2015 at 10:11 AM, Joel Kemp <notifications@github.com> wrote:

> Given the above I would then contact this fellow http://hugogiraudel.com/.
>
> Great tip. Will definitely do that when the sass bugs are ironed out.
>
> Covering all bases have you thought of a textmate and atom version too?
>
> Definitely, but I don't have the availability to handle anything but the
> sublime plugin. I'd love some help.
>
> The bulk of the logic is in nodejs npm modules, so the features can be
> reused across different editors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/sublime-dependents/issues/101#issuecomment-73558714>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Thanks @dkebler. I reached out to both of those twitter accounts.
