### ISSUE TITLE
Allow configuration of node path

### ISSUE THREAD

**Issue by robmcguinness** [mrjoelkemp/sublime-dependents#93]
```py
env['PATH'] += ':/usr/local/bin'
```

For some reason this plugin is not finding my node executable even though `node -v` works from the command line.  On my machine at work, Node is not installed in the default location because we have limited write access to certain folders.  

Would it be possible for this plugin to accept a path option in the configuration for Node?

```js
{
  "root": "public/assets/js",
  "config": "public/assets/js/config.js",  # Optional
  "sass_root": "public/assets/sass",       # Optional
  "exclude": ['jquery.js', 'require.js'],  # Optional
  "build_config": "public/assets/js/build.json", # Optional
  "node_path": "/some/custom/path" #Optional
}

```

**Comment by mrjoelkemp** [comment]
Hey @robmcguinness. Thanks for reporting. That's a great idea and totally possible. I'll add the fix.

**Comment by mrjoelkemp** [comment]
Pushed a fix for this in [the latest release](https://github.com/mrjoelkemp/sublime-dependents/releases/tag/v2.4.1). It will land in package control in about 45 minutes; you can check for the version to bump to v2.4.1 at https://packagecontrol.io/packages/Dependents.

Thanks again!

**Comment by robmcguinness** [comment]
@mrjoelkemp wow that was fast.  thanks!
